#! /bin/bash

function stop_sonic_services()
{
    echo "Stopping syncd..."
    docker exec -i syncd /usr/bin/syncd_request_shutdown --cold > /dev/null
    sleep 3
}


# Exit if not superuser
if [[ "$EUID" -ne 0 ]]; then
    echo "Please run as root" >&2
    exit 1
fi

PLATFORM=`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`
DEVPATH="/usr/share/sonic/device"
PLAT_REBOOT="platform_reboot"

# Stop syncd gracefully.
stop_sonic_services

if [ -x ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} ]; then
    sync
    sleep 3
    echo "Rebooting with platform ${PLATFORM} specific tool ..."
    ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT}
    exit 0
fi

# If no platform-specific reboot tool, just call /sbin/reboot
/sbin/reboot $@
