#! /bin/bash

DEVPATH="/usr/share/sonic/device"
PLATFORM=$(sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)
PLATFORM_LOG_SSD_HEALTH="platform_log_ssd_health"

FILE=${DEVPATH}/${PLATFORM}/${PLATFORM_LOG_SSD_HEALTH}
if [ -f "$FILE" ];then
    $FILE
fi

/sbin/fstrim -av

